server:
  port: 8090
spring:
  cloud:
    gateway:
      routes:
        - id: api_route
          uri: http://localhost:8124
          predicates:
             - Path=/api/**
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
# application.yml (Spring Boot)
dubbo:
  application:
    # 应用名称
    name: dubbo-springboot-demo-provider
    qosPort: 11112
    # 协议
  protocol:
    name: dubbo
    # 端口-1，客随机设置端口
    path: 20882
  # 注册中心 地址
  registry:
    id: nacos-registry
    # nacos://localhost:8848?namespace=5cbb70a5-xxx-xxx-xxx-d43479ae0932
    address: nacos://localhost:8848